name: CI - Tests
on: [push, pull_request]
jobs:
  test-ruby:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '2.6', '2.7' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run Ruby tests
      run: bundle exec rake